var annotated_dup =
[
    [ "details", null, [
      [ "PropertyToSample", "structdetails_1_1PropertyToSample.html", "structdetails_1_1PropertyToSample" ]
    ] ],
    [ "utils", "namespaceutils.html", "namespaceutils" ],
    [ "AmbientFluid", "classAmbientFluid.html", "classAmbientFluid" ],
    [ "BatchTracking", "classBatchTracking.html", "classBatchTracking" ],
    [ "BatchTrackingState", "classBatchTrackingState.html", "classBatchTrackingState" ],
    [ "BoundaryConditions", "classBoundaryConditions.html", "classBoundaryConditions" ],
    [ "BurialMedium", "classBurialMedium.html", "classBurialMedium" ],
    [ "BWRS", "classBWRS.html", "classBWRS" ],
    [ "Composition", "classComposition.html", "classComposition" ],
    [ "Config", "structConfig.html", "structConfig" ],
    [ "Discretizer", "classDiscretizer.html", "classDiscretizer" ],
    [ "DummyGas", "classDummyGas.html", "classDummyGas" ],
    [ "EnthalpyDiscretizer", "classEnthalpyDiscretizer.html", "classEnthalpyDiscretizer" ],
    [ "EquationOfState", "classEquationOfState.html", "classEquationOfState" ],
    [ "EquationOfStateBase", "classEquationOfStateBase.html", "classEquationOfStateBase" ],
    [ "FixedQValue", "classFixedQValue.html", "classFixedQValue" ],
    [ "FixedUValue", "classFixedUValue.html", "classFixedUValue" ],
    [ "GERG04", "classGERG04.html", "classGERG04" ],
    [ "GoverningEquationSolver", "classGoverningEquationSolver.html", "classGoverningEquationSolver" ],
    [ "GoverningEquationSolverBase", "classGoverningEquationSolverBase.html", "classGoverningEquationSolverBase" ],
    [ "HeatTransfer", "classHeatTransfer.html", "classHeatTransfer" ],
    [ "HeatTransferBase", "classHeatTransferBase.html", "classHeatTransferBase" ],
    [ "HeatTransferState", "structHeatTransferState.html", "structHeatTransferState" ],
    [ "IdealGas", "classIdealGas.html", "classIdealGas" ],
    [ "InternalEnergyDiscretizer", "classInternalEnergyDiscretizer.html", "classInternalEnergyDiscretizer" ],
    [ "Material", "classMaterial.html", "classMaterial" ],
    [ "MatrixEquation", "classMatrixEquation.html", "classMatrixEquation" ],
    [ "Physics", "classPhysics.html", "classPhysics" ],
    [ "Pipeline", "classPipeline.html", "classPipeline" ],
    [ "PipeWall", "classPipeWall.html", "classPipeWall" ],
    [ "RadialHeatTransfer", "classRadialHeatTransfer.html", "classRadialHeatTransfer" ],
    [ "Sampler", "classSampler.html", "classSampler" ],
    [ "Simulator", "classSimulator.html", "classSimulator" ],
    [ "Solver", "classSolver.html", "classSolver" ],
    [ "SteadyStateHeatTransfer", "classSteadyStateHeatTransfer.html", "classSteadyStateHeatTransfer" ],
    [ "TimeSeries", "classTimeSeries.html", "classTimeSeries" ],
    [ "TimeStep", "classTimeStep.html", "classTimeStep" ],
    [ "UnsteadyHeatTransfer", "classUnsteadyHeatTransfer.html", "classUnsteadyHeatTransfer" ]
];