var searchData=
[
  ['batch_443',['Batch',['../structBatchTrackingState_1_1Batch.html#adc84fe9beb0904662dd6f7be8f530f29',1,'BatchTrackingState::Batch']]],
  ['batches_444',['batches',['../classBatchTrackingState.html#ac6c02926fce1382453172e8f45feef8b',1,'BatchTrackingState']]],
  ['batchtrackingstate_445',['BatchTrackingState',['../classBatchTrackingState.html#a99cd4ca388452d924afdee2b9c75fd31',1,'BatchTrackingState::BatchTrackingState(const arma::vec &amp;gridPointsIncludingEndPoint, const arma::vec &amp;concentration=Composition::defaultComposition, const arma::uword nBatches=1)'],['../classBatchTrackingState.html#a3ba0083a296b38745216cd79dc9be99d',1,'BatchTrackingState::BatchTrackingState(const arma::vec &amp;gridPointsIncludingEndPoint, const std::vector&lt; Composition &gt; &amp;composition)']]],
  ['boundaryconditions_446',['BoundaryConditions',['../classBoundaryConditions.html#ae035d760fb05040d0c5859f4ca39aa0d',1,'BoundaryConditions::BoundaryConditions()'],['../classBoundaryConditions.html#af34b5b3cc9f92a36af9a4e7981cafc75',1,'BoundaryConditions::BoundaryConditions(const arma::mat &amp;boundaryConditionMat, const Composition &amp;inletComposition=Composition::defaultComposition, const Composition &amp;outletComposition=Composition::defaultComposition)'],['../classBoundaryConditions.html#a38c3e5bdce1ce2754a3d5ef2f4928a03',1,'BoundaryConditions::BoundaryConditions(const double inletFlow, const double outletFlow, const double inletPressure, const double outletPressure, const double inletTemperature, const double outletTemperature, const Composition &amp;inletComposition=Composition::defaultComposition, const Composition &amp;outletComposition=Composition::defaultComposition)'],['../classBoundaryConditions.html#af39d6df7dcb1201d3b0354d412171f01',1,'BoundaryConditions::BoundaryConditions(const Pipeline &amp;pipeline, const std::vector&lt; std::string &gt; &amp;boundarySettings={&quot;inlet&quot;, &quot;outlet&quot;, &quot;inlet&quot;})'],['../classBoundaryConditions.html#ab463e1988a44321c2ccbf3f0cee94969',1,'BoundaryConditions::BoundaryConditions(const SingleCondition inletFlow, const SingleCondition outletFlow, const SingleCondition inletPressure, const SingleCondition outletPressure, const SingleCondition inletTemperature, const SingleCondition outletTemperature, const Composition &amp;inletComposition=Composition::defaultComposition, const Composition &amp;outletComposition=Composition::defaultComposition)']]],
  ['boundaryterms_447',['boundaryTerms',['../classDiscretizer.html#ad113039c0c64227c3fabc06c40ddda48',1,'Discretizer']]],
  ['burialmedium_448',['BurialMedium',['../classBurialMedium.html#af66b79aec921ae0ba9fc8332f072d561',1,'BurialMedium::BurialMedium(const double conductivity, const double density, const double heatCapacity)'],['../classBurialMedium.html#a21bceb8da1dc8aa8aefec20542dce478',1,'BurialMedium::BurialMedium(const Material &amp;material)']]],
  ['bwrs_449',['BWRS',['../classBWRS.html#a99e1bbb5ad3181f8837d09f85da37752',1,'BWRS']]]
];
